### ISSUE TITLE
Include all protocol versions in Change Log version field

### ISSUE THREAD

**Issue by ptrus** [oasisprotocol/oasis-core#3402]
Currently we specify  Consensus, Runtime Host and Runtime Committee versions of a release in the Change Log. We should also include at least Tendermint (and ABCI) versions, as two releases could use same protocol versions but different Tendermint version resulting in incompatible releases. Probably doesn't hurt also including go toolchain version for completeness.

**Comment by tjanez** [comment]
Hmm... is this one really closed by #3528?

Wouldn't we still want to extend the [Change Log versions table](https://github.com/oasisprotocol/oasis-core/blob/master/docs/release-process.md#prepare-the-change-log):
```
| Protocol          | Version   |
|:------------------|:---------:|
| Consensus         | <VERSION> |
| Runtime Host      | <VERSION> |
| Runtime Committee | <VERSION> |
```

with info on Tendermint (and ABCI) and Go Toolchain versions?

**Comment by kostko** [comment]
The ABCI version is an internal detail which makes no sense to expose anywhere since Tendermint Core is in-process. The Tendermint Core version is no longer returned by `--version` as it is no longer provided by upstream in this manner (and we use a custom fork).

We could still report the versions of the underlying consensus block/p2p protocols though and also could include the Go Toolchain version. @ptrus proposed we just close this, but we could also restate it as mentioned.

**Comment by tjanez** [comment]
> The ABCI version is an internal detail which makes no sense to expose anywhere since Tendermint Core is in-process. The Tendermint Core version is no longer returned by `--version` as it is no longer provided by upstream in this manner (and we use a custom fork).

Agreed.

Sorry, I misread the diff in #3528 previously. I see now that all the Tendermint (and ABCI) version info is removed. So, this issue's main point is indeed no longer relevant.

> We could still report the versions of the underlying consensus block/p2p protocols though and also could include the Go Toolchain version. @ptrus proposed we just close this, but we could also restate it as mentioned.

Ok, all clear. Perhaps better to open a new issue when this becomes relevant.
