### ISSUE TITLE
stat /serverdir/node/internal.sock: no such file or directory

### ISSUE THREAD

**Issue by joesixpack** [oasisprotocol/oasis-core#3561]
This seems to happen about every 10 days or so.  Only a reboot will fix it.  I was able to generate it manually by editing the config and restarting the node a few times to capture a warn/error log.

[oasis.log](https://github.com/oasisprotocol/oasis-core/files/5671314/oasis.log)

**Comment by ptrus** [comment]
Hi, thanks for the report. 
The provided logs show that the reason for node crashing and restarting (causing the internal.sock to not be available) is bug related to querying the status endpoint before node initializes. This was fixed in https://github.com/oasisprotocol/oasis-core/pull/3534 and the fix is included in 20.12.3 release.
