### ISSUE TITLE
Flaky governance-upgrade test

### ISSUE THREAD

**Issue by ptrus** [oasisprotocol/oasis-core#3909]
The last part of the `governance-upgrade` test seems a bit flaky:

https://github.com/oasisprotocol/oasis-core/blob/05402d85a320a49ced5cebb78c157782ad227565/go/oasis-test-runner/scenario/e2e/runtime/governance_upgrade.go#L486-L497

Looking at logs sometimes this runtime p2p message from client-0 node is not propagated to the compute nodes. Waiting a bit before starting the client (via sleep) fixes the flakiness, but will debug a bit more to see why the p2p message from client is not propagated if started to soon.

**Comment by kostko** [comment]
We debugged this further with @jberci and it seems this is because libp2p is so nice that it will drop a message if there are no peers available (which seems racy). As a bonus it will also mark the message as seen even if it didn't actually manage to deliver it anywhere, so any retries are guaranteed to fail (at least until the cache timeout elapses, which is 120 seconds by default).

A workaround is to use a small bounded queue and check if there are any peers before calling libp2p's `Publish`. This should make it more robust during p2p stack initialization.
