### ISSUE TITLE
Seamless runtime upgrades

### ISSUE THREAD

**Issue by kostko** [oasisprotocol/oasis-core#4191]
Currently when a runtime upgrade is needed it will usually require the runtime to be paused for at least an epoch, until enough eligible nodes upgrade. This could be changed to be more seamless by:
* Compute nodes being able to configure and run multiple versions of a runtime and being able to announce this in the node descriptor.
* The runtime descriptor specifying the next version the runtime should upgrade to.
* The committee scheduler scheduling with the old version until enough eligible nodes indicate support for the new version and after that only scheduling the new version (and stop scheduling the old version).

**Comment by Yawning** [comment]
Some quick thoughts (that could go into the ADR)..

This will require some runtime descriptor format changes.  At a minimum there needs to be a way to express metadata for multiple versions.  The following fields are version independent:

 * ID: Otherwise it would be a different runtime.
 * EntityID: Being able to transfer ownership on each version seems dangerous, and would add non-trivial amounts of complexity.
 * Genesis: Upgrades do not annihilate history.
 * Kind: If this changes, it should be a different runtime.

The following fields are probably "ok" to be changed on each version, but may require some discussion, because while there would be a clear benefit to doing so, things would be significantly more complex:

 * TEEHardware: Should we support migrating between TEE environments between versions?
 * Keymanager: Likewise, should we support migrating to a new key manager implmementation/deployment between versions?

The per-version runtime metadata needs a field added that, at a minimum expresses the earliest possible epoch at which a particular version of a runtime should be scheduled.  I would strongly prefer a "upgrade at" epoch.

As a matter of foot + gun prevention and to make deployment easier for operators, we should:

 * Allow nodes registration to succeed with unknown runtime versions (so that deployment preparation can be done in advance).  The scheduler MUST ignore runtime versions that it does not know about (ie: The runtime descriptor MUST be treated as canonical).
 * Make it extremely hard for a node to spin up an incorrect runtime binary (The worker should query each runtime for it's runtime ID + version, before registering).
 * Figure out a plan for how we want upgrades to happen, and start planning on what our documentation will look like.

Assuming that all the foot + gun prevention measures are in place, I envision an upgrade process to look something like:

 0. Lots of development + testing.
 1. A new runtime version is tagged, binaries are built, configuration changes are recommended.
 2. Node operators update their configuration.
 3. When sufficient nodes have updated, pick an upgrade epoch, update the runtime descriptor (Tooling to easily monitor this is needed).
 4. Sit around and wait.  Some assurance that the upgrade will happen at the scheduled time is provided due to the update being staged, and the switchover time being picked after enough nodes are ready.  Failures due to nodes dropping out at the epoch are identical to "insufficient nodes to form a committee, with the old binary".

This does diverge from the proposed upgrade workflow in the original issue, however it provides a deterministic switchover time, while preserving the property that upgrades will only happen when sufficient nodes are ready.

**Comment by kostko** [comment]
> The following fields are probably "ok" to be changed on each version, but may require some discussion, because while there would be a clear benefit to doing so, things would be significantly more complex:
> 
> * TEEHardware: Should we support migrating between TEE environments between versions?
> * KeyManager: Likewise, should we support migrating to a new key manager implementation/deployment between versions?

I would say this stays as it is now with changes in these not being allowed. Currently the only allowed change is with the KeyManager field where one can go from "no key manager" to "there is now a key manager". But changing a key manager once set is not allowed.
 
> The per-version runtime metadata needs a field added that, at a minimum expresses the earliest possible epoch at which a particular version of a runtime should be scheduled. I would strongly prefer a "upgrade at" epoch.

Agreed.

> As a matter of foot + gun prevention and to make deployment easier for operators, we should:
> 
> * Allow nodes registration to succeed with unknown runtime versions (so that deployment preparation can be done in advance).  The scheduler MUST ignore runtime versions that it does not know about (ie: The runtime descriptor MUST be treated as canonical).

Yeah this already happens now, the scheduler will ignore any versions which are not like in the runtime descriptor.

> * Make it extremely hard for a node to spin up an incorrect runtime binary (The worker should query each runtime for it's runtime ID + version, before registering).

Agreed.

> This does diverge from the proposed upgrade workflow in the original issue, however it provides a deterministic switchover time, while preserving the property that upgrades will only happen when sufficient nodes are ready.

Agreed, the proposed workflow where the upgrade is scheduled for a predetermined epoch makes more sense to me. As long as it can also be cancelled (e.g. by submitting another descriptor).

**Comment by Yawning** [comment]
Separate from the runtime descriptor, there needs to be a "most recent runtime version" that gets ratcheted up on the consensus side when upgrades are published, to prevent rollbacks, that is preserved across dump/restore consensus updates.  I would probably go a step further (and bloat consensus state) by storing a `runtime ID -> (version, ValidFrom, descriptor digest)` table.

If something goes wrong with an upgrade, a "downgrade" should be done by incrementing the version.

**Comment by Yawning** [comment]
> Agreed, the proposed workflow where the upgrade is scheduled for a predetermined epoch makes more sense to me. As long as it can also be cancelled (e.g. by submitting another descriptor).

I guess this is possible.  We could add a monotonically increasing serial number to the descriptor.  As long as this doesn't try to allow rolling back versions, I have no problems with this.
