### ISSUE TITLE
Add new consensus governance voting mechanism specifying % of total stake needing to vote yes

### ISSUE THREAD

**Issue by tjanez** [oasisprotocol/oasis-core#4309]
##### SUMMARY
Currently, there are two [parameters controling consensus governance voting](https://docs.oasis.dev/oasis-core/high-level-components/index/services/governance#consensus-parameters):
- `quorum` (uint8: [0,100]) specifies the minimum percentage of voting power that needs to be cast on a proposal for the result to be valid.
- `threshold` (uint8: [0,100]) specifies the minimum percentage of `VoteYes` votes in order for a proposal to be accepted.

Consider replacing both of those parameters with a single parameter (i.e. a new threshold) that would specify % of total stake (i.e. voting power) that needs to cast `VoteYes` votes in order for a proposal to be accepted.

##### ISSUE TYPE
- Feature Idea

**Comment by Yawning** [comment]
While I am ok with some fine tuning being possible, I would be extremely reluctant to allow the new parameter to be set to anything less than `2f + 1` of the total voting power available.

**Comment by kostko** [comment]
Yeah so currently we have a sanity check that ensures the product of quorum and threshold is >2/3:
https://github.com/oasisprotocol/oasis-core/blob/ded43efceef9d8f5bd64de0f22f9cec32909d32e/go/governance/api/sanity_check.go#L25-L28

I agree that we should keep enforcing this constraint.

**Comment by Yawning** [comment]
I'm still not sure this is an amazing idea, because it doesn't improve on one of the problems of this design.  It is really easy to meet both `quorum` + `threshold` or the new proposed `stake_threshold` targets when the validator set is small (and we currently allow consensus to operate with a rather small number of active validators).

What we probably really want is something along the lines of "minimum percentage of the total global stake (including nodes that are offline and not in the validator set) that needs to cast VoteYes`, but that has it's own set of problems (it is trivial to create situations where it is impossible to pass governance proposals).

Thoughts welcome.
