### ISSUE TITLE
Control SGX use with runtime.mode

### ISSUE THREAD

**Issue by pro-wh** [oasisprotocol/oasis-core#4869]
##### SUMMARY

Currently we use the presence of a `runtime.sgx.loader` setting. But it might be simpler to have separate modes, e.g. 'client' and 'confidential client.' That way, if you download the loader binary and merely inform oasis-node of where the loader is, you can still easily switch to using a non-SGX copy of the runtime.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

go runtime initialization

##### ADDITIONAL INFORMATION

We've encountered a few issues in node operator support where the operator wanted to run a non-SGX node, but the node tried (unsuccessfully) to load the SGX version of a runtime. Maybe this will make it clearer how to prevent that.

**Comment by kostko** [comment]
Master currently has `runtime.environment` in addition to `runtime.mode`, because for clients you would need two extra modes (e.g. `client-confidential` and `client-stateless-confidential`).

So I believe this is already solved in master although slightly differently. A client can set the following to use the SGX runtime:
```yaml
runtime:
    mode: client
    environment: sgx
    # ...
```

Otherwise the clients will always prefer ELF binaries and compute nodes will always require SGX for confidential runtimes and fail if the SGX loader is not configured.

Note that this is not currently the case in 22.1.x.

**Comment by pro-wh** [comment]
ok let's go with runtime.environment as described above and implemented in master
